# Generated by Django 3.1.4 on 2021-01-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='1234', max_length=32),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
